FROM scratch

# 解压系统命令
ADD rootfs.tar.xz /
# 更新源
RUN echo 'deb http://deb.debian.org/debian stretch main' > /etc/apt/sources.list && \
	echo 'deb http://security.debian.org/debian-security stretch/updates main' >> /etc/apt/sources.list && \
	echo 'deb http://deb.debian.org/debian stretch-updates main' >> /etc/apt/sources.list && \
	apt-get update && \
	#Install java8
	apt install -y openjdk-8-jdk openjdk-8-jre maven && \
	#Install mysql-server
	apt-get -y install mysql-server \
	    apache2 \
		php7.0 \
		libapache2-mod-php7.0 && \
	    apt-get clean && \
	#Install Node 8 && 设置源
	apt-get -y install build-essential curl&& \
		curl -sL https://deb.nodesource.com/setup_8.x | bash && \
		apt-cache showpkg nodejs && \
		apt-get install --yes nodejs=8.17.0-1nodesource1 && \
		node -v && \
		npm -v && \ 
		# 设置淘宝源
		# npm config set registry https://registry.npm.taobao.org && \ 
		npm i -g nodemon && \
		nodemon -v && \
		apt-get clean	
